<start> ::= <expr>
<expr>  ::= <expr>+<expr>|
            <expr>-<expr>|
            <expr>*<expr>|
            pdiv(<expr>,<expr>)|
            np.sin(<expr>)|
            np.cos(<expr>)|
            np.exp(<expr>)|
            plog(<expr>)|
            x[0]|
            1.0